version: "3.8"
services:
    office-tracker:
        build: .
        image: futurice/office-tracker:latest
        tty: true
        ports:
            - "3000:3000"
        depends_on:
            - db

    db:
        image: postgres:12.3
        environment:
            POSTGRES_DB: office
            POSTGRES_PASSWORD: example_password
