name: office-tracker
version: 0.1.0.0
homepage: https://github.com/futurice/office-tracker#readme
license: MIT
author: Jan van Brügge
maintainer: jan.van.brugge@futurice.com
copyright: 2020 Jan van Brügge
category: Web
extra-source-files:
    - README.md

default-extensions:
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - DerivingStrategies
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TypeOperators

dependencies:
    - base >= 4.7 && < 5
    - aeson
    - servant
    - servant-server
    - text
    - time
    - wai
    - warp

executables:
    office-tracker:
        source-dirs: src
        main: Main.hs
