name: office-tracker
version: 0.1.0.0
homepage: https://github.com/futurice/office-tracker#readme
license: MIT
author: Jan van Brügge
maintainer: jan.van.brugge@futurice.com
copyright: 2020 Jan van Brügge
category: Web

default-extensions:
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - DerivingStrategies
    - FlexibleContexts
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - ScopedTypeVariables
    - TypeOperators

dependencies:
    - base >= 4.7 && < 5
    - aeson
    - binary
    - bytestring
    - mtl
    - postgresql-simple
    - resource-pool
    - servant
    - servant-server
    - text
    - time
    - wai
    - warp
    - yaml

executables:
    office-tracker:
        source-dirs: src
        main: Main.hs
