name: office-tracker
version: 0.1.0.0
homepage: https://github.com/futurice/office-tracker#readme
license: MIT
author: Jan van Brügge
maintainer: jan.van.brugge@futurice.com
copyright: 2020 Jan van Brügge
category: Web

default-extensions:
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - DerivingStrategies
    - DuplicateRecordFields
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - NamedFieldPuns
    - OverloadedLabels
    - OverloadedStrings
    - ScopedTypeVariables
    - TypeApplications
    - TypeFamilies
    - TypeOperators

ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Werror

dependencies:
    - base >= 4.7 && < 5
    - aeson
    - aeson-optics
    - base64
    - binary
    - bytestring
    - cassava
    - cookie
    - exceptions
    - http-client
    - http-client-tls
    - http-media
    - http-types
    - insert-ordered-containers
    - jose
    - lens
    - lens-aeson
    - mtl
    - network-uri
    - openapi3
    - openid-connect
    - optics
    - postgresql-simple
    - resource-pool
    - retry
    - servant
    - servant-cassava
    - servant-multipart
    - servant-server
    - servant-swagger
    - servant-swagger-ui
    - swagger2
    - text
    - time
    - vault
    - wai
    - wai-app-static
    - wai-cors
    - warp
    - yaml

executables:
    office-tracker:
        source-dirs: src
        main: Main.hs
