name: office-tracker
version: 0.1.0.0
homepage: https://github.com/futurice/office-tracker#readme
license: MIT
author: Jan van Brügge
maintainer: jan.van.brugge@futurice.com
copyright: 2020 Jan van Brügge
category: Web

default-extensions:
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - DerivingStrategies
    - FlexibleContexts
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - ScopedTypeVariables
    - DuplicateRecordFields
    - TypeOperators

ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Werror

dependencies:
    - base >= 4.7 && < 5
    - aeson
    - binary
    - bytestring
    - exceptions
    - http-types
    - insert-ordered-containers
    - lens
    - mtl
    - postgresql-simple
    - resource-pool
    - retry
    - servant
    - servant-server
    - servant-swagger
    - swagger2
    - text
    - time
    - wai
    - wai-cors
    - warp
    - yaml

executables:
    office-tracker:
        source-dirs: src
        main: Main.hs
