name: Build
on:
    push:
        paths-ignore:
            - '**.md'

jobs:
    ci:
        name: Build and Deploy
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup buildx
              uses: docker/setup-buildx-action@v1

            - name: Cache docker layers
              uses: actions/cache@v1
              with:
                  path: /tmp/docker-cache
                  key: docker-cache-${{ hashFiles('backend/stack.yaml.lock') }}-${{ hashFiles('backend/office-tracker.cabal') }}-${{ hashFiles('frontend/package-lock.json') }}-1
                  restore-keys: |
                      docker-cache-

            - name: Cache buildkit cache
              uses: actions/cache@v1
              with:
                path: /tmp/buildkit-cache
                key: buildkit-cache-${{ hashFiles('backend/stack.yaml.lock') }}
                restore-keys: |
                    buildkit-cache-

            - name: Move buildkit cache to correct location
              run: '[ -e /tmp/buildkit-cache ] && sudo mv /tmp/buildkit-cache /var/lib/docker/buildkit || true'

            - name: Build container
              run: |
                  docker buildx build \
                    --cache-from "type=local,src=/tmp/docker-cache" \
                    --cache-to "type=local,dest=/tmp/docker-cache,mode=max" \
                    --output "type=docker" \
                    --tag futurice/futulog:$(git rev-parse --short HEAD) .

            - name: Move buildkit cache to tmp
              run: sudo mv /var/lib/docker/buildkit /tmp/buildkit-cache && sudo chmod -R +r /tmp/buildkit-cache

            - name: Deploy to futuEKS
              run: ./deploy.sh cd
              if: github.ref == 'refs/heads/master'
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  KUBECONFIG: ${{ secrets.KUBECONFIG }}
