name: Build
on:
    push:
        paths-ignore:
            - '**.md'

jobs:
    backend:
        name: Build Backend
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.stack
                  key: stack-store-${{ hashFiles('backend/stack.yaml.lock') }}-${{ hashFiles('backend/office-tracker.cabal') }}
                  restore-keys: |
                      stack-store-${{ hashFiles('backend/stack.yaml.lock') }}-
                      stack-store-

            - name: Build backend
              run: cd backend && stack build

            - name: Copy executable
              run: cd backend && cp "$(stack path --dist-dir)/build/office-tracker/office-tracker" .

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: backend
                  path: backend/office-tracker

    frontend:
        name: Build frontend
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: frontend/node_modules
                  key: npm-store-${{ hashFiles('frontend/package-lock.json') }}
                  restore-keys: |
                      npm-store-

            - name: Install dependencies
              run: cd frontend && npm ci

            - name: Build project
              run: cd frontend && npm run build

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: frontend
                  path: frontend/build/

    docker:
        name: Build docker container
        runs-on: ubuntu-18.04
        needs: [backend, frontend]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Download backend
              uses: actions/download-artifact@v2
              with:
                  name: backend

            - name: Download frontend
              uses: actions/download-artifact@v2
              with:
                  name: frontend
                  path: frontend/build

            - name: Build docker container
              run: docker build -t "futurice/office-tracker:$(git rev-parse --short HEAD)" -f CI_Dockerfile .
