name: Build
on:
    push:
        paths-ignore:
            - '**.md'

jobs:
    ci:
        name: Build and Deploy
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup buildx
              uses: docker/setup-buildx-action@v1

            - name: Cache docker layers
              uses: actions/cache@v1
              with:
                  path: /tmp/docker-cache
                  key: docker-1-cache-${{ hashFiles('backend/stack.yaml.lock') }}-${{ hashFiles('backend/office-tracker.cabal') }}-${{ hashFiles('frontend/package-lock.json') }}
                  restore-keys: |
                      docker-1-cache-

            - name: Cache buildkit cache
              uses: actions/cache@v1
              with:
                path: /tmp/buildkit-cache
                key: buildkit-1-cache-${{ hashFiles('backend/stack.yaml.lock') }}
                restore-keys: |
                    buildkit-1-cache-

            - name: Move buildkit cache to correct location
              run: '[ -e /tmp/buildkit-cache ] && sudo mv /tmp/buildkit-cache /var/lib/docker/buildkit || true'

            - name: Build container
              run: |
                  docker buildx build \
                    --cache-from "type=local,src=/tmp/docker-cache" \
                    --cache-to "type=local,dest=/tmp/docker-cache,mode=max" \
                    --output "type=docker" \
                    --tag play/futulog:$(git rev-parse --short HEAD) .

            - name: Move buildkit cache to tmp
              run: sudo mv /var/lib/docker/buildkit /tmp/buildkit-cache && sudo chmod -R +r /tmp/buildkit-cache

            - name: Deploy to futuEKS
              run: |
                  echo "$KUBE_YAML" > kubeconfig
                  R=$(aws sts assume-role --role-arn "$AWS_ROLE_TO_ASSUME" --role-session-name AWSCLI-Session)
                  export AWS_ACCESS_KEY_ID=$(echo "$R"|jq -r '.Credentials.AccessKeyId')
                  export AWS_SECRET_ACCESS_KEY=$(echo "$R"|jq -r '.Credentials.SecretAccessKey')
                  export AWS_SESSION_TOKEN=$(echo "$R"|jq -r '.Credentials.SessionToken')
                  ./deploy.sh cd
              if: github.ref == 'refs/heads/master'
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                  KUBE_YAML: ${{ secrets.KUBE_YAML }}
                  AWS_DEFAULT_REGION: eu-central-1
                  KUBECONFIG: kubeconfig
